export {
  fetchPortalDashboard,
  fetchStudentCourses,
  fetchStudentAttendance,
  fetchStudentFees,
  fetchTeachersDirectory,
  fetchStudentResults,
  fetchNotifications,
  markNotificationsRead,
  fetchReportsData,
  fetchAdminData,
  fetchDepartments,
  adminUpsertStudent,
  adminDeleteStudent,
  adminUpsertTeacher,
  adminDeleteTeacher,
  adminUpsertCourse,
  adminDeleteCourse,
  adminEnrollStudent,
  adminUnenrollStudent,
  adminAssignInstructor,
} from "./data";
